p8105\_hw1\_kq2127
================
Kristal Quispe
9/17/2019

# Problem 1

``` r
p1_df = tibble(
  sample = rnorm(8),
  gr_th_0 = sample > 0, 
  vec_char = c("My", "complete", "full", "name", "is", "Jane", "Reed", "Doe"),
  vec_factor = factor(c("Green", "Red", "Red", "Blue", "Green", "Green", "Blue", "Blue"))
)


mean(pull(p1_df, sample))
```

    ## [1] -0.115115

``` r
mean(pull(p1_df, gr_th_0))
```

    ## [1] 0.375

``` r
mean(pull(p1_df, vec_char))
```

    ## Warning in mean.default(pull(p1_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(p1_df, vec_factor))
```

    ## Warning in mean.default(pull(p1_df, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

When I take the mean of the first two variables in my data frame I get a
result. The mean variable sample is -0.115115 and the mean of variable
gr\_th\_0 is 0.375 . I was not able to take the mean of the last two
variables, vec\_char and vec\_factor because these two variables are not
numeric or logical.

``` r
as.numeric(pull(p1_df, gr_th_0))

as.numeric(pull(p1_df, vec_char))

as.numeric(pull(p1_df, vec_factor))
```
